### ISSUE TITLE
Enable Connmark support for Wireguard

### ISSUE THREAD

**Issue by rg9400** [nathanchance/WSL2-Linux-Kernel#11]
I apologize as this is well above my understanding, but I wanted to use wireguard in WSL2. I tried using your kernel, but it failed for the reason listed in this thread.

https://www.reddit.com/r/bashonubuntuonwindows/comments/jk4x24/is_there_a_way_to_run_wireguard_within_wsl2/

Seems it requires this flag - `CONFIG_NETFILTER_XT_MATCH_CONNMARK` to be enabled. Any chance you can enable it for the next version of the kernel?

**Comment by nathanchance** [comment]
Sure I can enable this flag.

**Comment by nathanchance** [comment]
This has been enabled in v55. Please let me know if it does not work.

**Comment by rg9400** [comment]
Thanks! FYI, it worked perfectly
