### ISSUE TITLE
Pull Clock Sync bug fix from Insider WSL Kernel

### ISSUE THREAD

**Issue by rg9400** [nathanchance/WSL2-Linux-Kernel#13]
There's a bug in the current production kernel on WSL that seems to exist in this custom kernel as well where the clock in WSL will lose sync with the host clock over time. 

This was fixed in an insider build of the kernel. You can read the note here: https://devblogs.microsoft.com/commandline/servicing-the-windows-subsystem-for-linux-wsl-2-linux-kernel/#bug-fix-clock-sync

GHI: https://github.com/microsoft/WSL/issues/5324

The relevant kernel is at https://github.com/microsoft/WSL2-Linux-Kernel/releases/tag/linux-msft-wsl-5.10.16.3

Not sure if this is easy to pull into yours, but if it is, I would greatly appreciate it as I run a 2FA service in WSL that obviously requires precise time syncing.

EDIT: 
Relevant Kernel bugs  
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hv/hv_util.c?id=b46b4a8a57c377b72a98c7930a9f6969d2d4784e
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hv/hv_util.c?id=90b125f4cd2697f949f5877df723a0b710693dd0

**Comment by nathanchance** [comment]
My kernel already has those patches by the nature of it being based on linux-next, which is the bleeding edge Linux tree, so I am not sure how my kernel could have the problem you mention.

**Comment by rg9400** [comment]
I am getting the below response when running `uname -r` which I believe corresponds to your latest kernel. 
`5.12.0-rc7-next-20210416-microsoft-cbl`

I definitely have the time sync issue as `ntpdate`  fixed a 12 second offset just today.

Though maybe there was more involved on the Windows end to fix it considering it is related to syncing with the host system. All of this is above my knowledge/understanding, so I may be missing something related to how the bug was fixed on Microsoft's end.

**Comment by nathanchance** [comment]
Yes, that would be the latest.

I can only go off of what Microsoft says and they claim that they only needed upstream Linux changes to fix the issue, which I have. Are you sure that the stock kernel is fixed? If so, then it is entirely possible that it regressed again upstream.

**Comment by rg9400** [comment]
Unfortunately no, I do not have much knowledge on this topic outside the links I shared. Looking at the Microsoft blog post, it does seem like they are saying they just updated the Linux kernel to fix the issue, so as you said, it might have regressed in a later build upstream as this kernel is further ahead than 5.10.

I guess you can close this issue if you want since there's probably nothing else to be done at your end.
