### ISSUE TITLE
Stability issues with v59

### ISSUE THREAD

**Issue by AntonOfTheWoods** [nathanchance/WSL2-Linux-Kernel#14]
I don't unfortunately have any logs (yet) but I am having regular WSL crashes since updating to v59 from (if memory serves) v56. I don't remember changing anything else. It always seems to happen when the host comes out of (deep) sleep. Very, very occasionally I had such issues (once every 1-2 months max) with previous kernels but now I'm getting them every 1-2 days. I am not having any issues, except when coming out of sleep on the host.

Is anyone else having these issues? Should I be looking somewhere other than the new v59 kernel (ie., I must have forgotten some other update)? If this is the right place, any pointers on what logs I should be checking? 

Thanks!

**Comment by nathanchance** [comment]
I have two different devices that I regularly sleep and I have never had any issues of instability when resuming. Are you talking about just sleeping the computer or hibernating it?

I guess I will probably have to let other poeple chime in on whether or not they have similar experiences. What CPU does your computer have? What version of Windows are you running? I am not sure what kind of logs you can gather, do you get an error message?

**Comment by AntonOfTheWoods** [comment]
> I have two different devices that I regularly sleep and I have never had any issues of instability when resuming. Are you talking about just sleeping the computer or hibernating it?

Actually it's hibernate. <rant> I forgot that the Windows engineers think it's Ok to start your computer, install updates and reboot without you being able to stop it if you just sleep. That's awesome fun when your (expensive, new) laptop has terrible heat dissipation and can overheat and physically damage components, particularly when in a laptop bag </rant>

> I guess I will probably have to let other poeple chime in on whether or not they have similar experiences. What CPU does your computer have? What version of Windows are you running? I am not sure what kind of logs you can gather, do you get an error message?

```
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
Installed RAM	16.0 GB (15.8 GB usable)
```
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎16 ‎Apr ‎2020
OS build	19043.964
Experience	Windows Feature Experience Pack 120.2212.3740.0
```
Ok, so that has just suggested a possibly more likely candidate - the host OS. As mentioned I occasionally got crashes so might have got them also between updating the host and installing the WSL kernel. Others might have the same host kernel too though!

**Comment by nathanchance** [comment]
Hopefully things have been better. I am going to close this up for now, as I doubt this is strictly related to the kernel and even if it is, I do not have the tools to debug what is going on as WSL is a bit of a black box.
