### ISSUE TITLE
WSLg support?

### ISSUE THREAD

**Issue by AskAlice** [nathanchance/WSL2-Linux-Kernel#15]
I'm running insider edition with what I presume to be an official build of https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-5.10.y

I was able to get nested virtualization working on AMD without a hitch with the latest insider edition kernel built in april, as well as WSLg.

Does your kernel support WSLg?

**Comment by nathanchance** [comment]
It should as I have the `dxgknrl` patches but I am not on the Insiders Dev channel to be able to test it and I am most likely not going to be able to fix any issues if there are any due to that. Feel free to let me know though!

**Comment by AskAlice** [comment]
Thanks, I'll try it out
