### ISSUE TITLE
Virtualbox kernel module

### ISSUE THREAD

**Issue by AskAlice** [nathanchance/WSL2-Linux-Kernel#16]
Is it possible to follow a process similar to this https://github.com/darlinghq/darling/issues/260#issuecomment-530184521
to install virtualbox-dkms into the WSL2 kernel?

**Comment by nathanchance** [comment]
My kernel explicitly disables kernel modules to reduce attack surface. If you want the ability to use dkms, you will need to re-enable modules and build the kernel yourself (it is not that difficult and does not require that powerful of a computer).
