### ISSUE TITLE
WSL2g doesn't start with Clang Built WSL2 Kernel v60

### ISSUE THREAD

**Issue by akuropka** [nathanchance/WSL2-Linux-Kernel#19]
Microsoft Windows [Version 10.0.22000.65] x64 Enterprise
Ubuntu on Windows Community Preview 
upgraded to Ubuntu Impish Indri (development branch) release 21.10
WSL version 2 with g

My Linux doesn't start while using this kernel. 
Using standard kernel or self-compiled one based on MS-sources works (5.10.43.3).
WSL shutdown takes long time.

How to trace further?

![20210713_162050_ubuntupreview](https://user-images.githubusercontent.com/22570574/125469123-d865509e-5562-45d9-9680-ef4f450d1ed4.png)

**Comment by nathanchance** [comment]
This is an Insiders Dev build, correct? I do not usually support the Dev builds because they move so fast. It could be any number of things but it is most likely a configuration change. You might be able to grab `/proc/config.gz` and upload it for me to take a look at. Otherwise, there is not much that can be done to see why it is not booting as WSL2 is a bit of a black box.

**Comment by akuropka** [comment]
Yeah, it's Dev... 😬
It was more like a question how to trace it down.
Attached the files for reference...
[config.diff.txt](https://github.com/nathanchance/WSL2-Linux-Kernel/files/6811278/config.diff.txt)
[config_5.10.txt](https://github.com/nathanchance/WSL2-Linux-Kernel/files/6811279/config_5.10.txt)
[config_5.13.txt](https://github.com/nathanchance/WSL2-Linux-Kernel/files/6811280/config_5.13.txt)

**Comment by Trass3r** [comment]
Does it result in high CPU usage of the vmmem process?
When I trigger the vGPU support in W10 21H2 via `clinfo` with this kernel (latest release, self-built tip, clang/gcc built, with/without lto) I get a similar behavior. It works with the default 5.10 kernel.

**Comment by nathanchance** [comment]
It is entirely possible. I do not currently have any interest in debugging this, as I do not use WSLg. I'll take any fixes for this that come my way though.

**Comment by akuropka** [comment]
**Update:**
I didn't check out this build for some time (I kept using v59), however it behaves with the updated WSL setup the same way as v61 (#21).
