### ISSUE TITLE
[Clang Built WSL2 Kernel v61] dxgk:err: invalid event pointer / unexpected packet type

### ISSUE THREAD

**Issue by akuropka** [nathanchance/WSL2-Linux-Kernel#21]
Microsoft Windows [Version 10.0.22000.466] (also tested on .376 and .434 before)
Microsoft.WSL_0.51.0.0 (also tested on .50.2)

WSL starts (motd is shown in Ubuntu) but hangs after ~ 4 seconds and producing only those errors indefinitely:

> dxgk:err: unexpected packet type
> dxgk:err: invalid event pointer

`wsl --shutdown` doesn't work either anymore (hangs).

[WSL_Console.zip](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7875294/WSL_Console.zip)
![20220115_164737_Taskmgr](https://user-images.githubusercontent.com/22570574/149628352-7e58d9c5-6e3b-47dd-ac19-1689366f077a.png)

**Comment by nathanchance** [comment]
Can you try [this image](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7875611/bzImage.zip) and see if it is any better? It uses the `dxgkrnl` driver that was just posted upstream, which will likely have better compatibility with linux-next.

Full disclosure, I do not use WSLg, I only include the patches on the off chance that it works. If it doesn't, I will just rip the patches out and say that WSLg is unsupported with this kernel (not sure if you are actually using it or not).

There could also be some incompatibility with the store version of WSL and this kernel, I have no idea, as I am still on Windows 10.

**Comment by akuropka** [comment]
Yeah, that image does the trick 😀👍.

The store package comes with WSLg included though I am not using it actively on this machine.
However, first testing shows this one seems to be compatible with the store version of WSL incl. WSLg with hardware acceleration.

Thank you so much!

**Comment by nathanchance** [comment]
Thanks a lot, I will release v62 here shortly. I assume this obsoletes your earlier report (#19) as well?

**Comment by akuropka** [comment]
Yes, with the expected release of v62 both issues are obsolete.
