### ISSUE TITLE
Ubuntu 20.04 suddenly exit on V62 (never meet before)

### ISSUE THREAD

**Issue by LeCmnGend** [nathanchance/WSL2-Linux-Kernel#22]
After turn on again, it show:
      An existing connection was forcibly closed by the remote host. 
      Press any key to continue...
My .wslconfig file: (w10 update 21h2 16gb ram amd4800h 8 core 16 process)
[wsl2]
kernel = C:\\Users\\bzImage
processors=13
memory=9.5GB
swap=0.5GB
swapFile=%USERPROFILE%\AppData\Local\Temp\swap.vhdx
localhostForwarding=true

**Comment by nathanchance** [comment]
Is that kernel path right? I would have expected it to be somewhere in your user's folder (I.e., `C:\Users\you`), rather than the Users folder.

Otherwise, I do not recall ever seeing that error. Does it happen all the time?

**Comment by LeCmnGend** [comment]
I have right path,(2 user profile so i paste in c:\user :)) ) 
Sometime it happens.
Newest today:
first: I open ubuntu  then repo sync (crDroid source)
second: open another ubuntu windows then git clone (my device tree)
i think it cause problem.
try to restore host by default by this solution but it is not working:
https://github.com/microsoft/WSL/issues/4105

**Comment by LeCmnGend** [comment]
How can i grap Ubuntu app logs sir?

**Comment by nathanchance** [comment]
I have no idea unfortunately. If you remove the `kernel` line, does it still occur?

**Comment by LeCmnGend** [comment]
> I have no idea unfortunately. If you remove the `kernel` line, does it still occur?

Something conflict in v62 sir, v61 work fine,
use kernel from default no suddenly exit (but very lag and slow)

**Comment by LeCmnGend** [comment]
After a day in v61, it works fine sir.

**Comment by nathanchance** [comment]
WSL is pretty much a black box for debugging so since my builds work perfectly fine, I cannot really do much here. I'll probably build a v63 here in the next couple of days that could resolve your issue by chance.

**Comment by LeCmnGend** [comment]
Try v62 again today. When compile rom it eat all my ram (like normal) and then force stop again. No luck for me.

**Comment by nathanchance** [comment]
Could you try [this kernel](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7938132/bzImage.zip) and see if there is any improvement? There was [an out of bounds array access](https://lore.kernel.org/r/YfCVi%2FTGD9Dnf9CG@dev-arch.archlinux-ax161/) that showed up with the latest version of the `dxgkrnl` driver that I have now fixed, which could potentially be problematic. Additionally, this has a few more `-next` versions in it, which could fix a transient bug.

**Comment by LeCmnGend** [comment]
> Could you try [this kernel](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7938132/bzImage.zip) and see if there is any improvement? There was [an out of bounds array access](https://lore.kernel.org/r/YfCVi%2FTGD9Dnf9CG@dev-arch.archlinux-ax161/) that showed up with the latest version of the `dxgkrnl` driver that I have now fixed, which could potentially be problematic. Additionally, this has a few more `-next` versions in it, which could fix a transient bug.

the file is empty sir

**Comment by nathanchance** [comment]
Weird, don't know how that happened.... Try [this one](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7943227/bzImage.zip).

**Comment by LeCmnGend** [comment]
> Weird, don't know how that happened.... Try [this one](https://github.com/nathanchance/WSL2-Linux-Kernel/files/7943227/bzImage.zip).

i will reply tomorrow, 15 min and still not exist :-D

**Comment by LeCmnGend** [comment]
When i compile rom:
/bin/sh: 1: Cannot fork

Ninja 137 err code.
Both search google all cause by out of memory error.
Back to 61 and still fine. So stranger

**Comment by nathanchance** [comment]
The heaviest memory intensive workload that I have at this point is compiling a kernel with full LTO, which I can complete just fine with that kernel. My machine does have a Ryzen 9 3900X and 64GB of RAM but I only give WSL2 8 cores and 16GB of RAM.

At this point, I am not really sure what could be going wrong.

**Comment by LeCmnGend** [comment]
> 

Fixed: Increase swapFile to 64gb, lol
but v63 is still suddenly exit, which is inluce in this.zip doesnt have in v63 sir?

**Comment by nathanchance** [comment]
There is nothing in that zip that is not in v63.

**Comment by LeCmnGend** [comment]
> There is nothing in that zip that is not in v63.

thank again, this zip (maybe 62.5 work fine for me too)
