### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by willzyx-hub** [nathanchance/WSL2-Linux-Kernel#23]
Hello just to ask is there anyway to enable usb support on wsl can we compile kernel with usb support on it ? Thanks

**Comment by nathanchance** [comment]
The WSL2 kernel already has USB support enabled:

https://github.com/nathanchance/WSL2-Linux-Kernel/blob/355c633836e4e8ed050714879b7db38378b79f79/arch/x86/configs/wsl2_defconfig#L398-L405

If you are talking about needing a specific driver, you can use the `menuconfig` target to enable a driver that you need.

As this is not something specific to this kernel, closing.

**Comment by willzyx-hub** [comment]
> The WSL2 kernel already has USB support enabled:
> 
> https://github.com/nathanchance/WSL2-Linux-Kernel/blob/355c633836e4e8ed050714879b7db38378b79f79/arch/x86/configs/wsl2_defconfig#L398-L405
> 
> If you are talking about needing a specific driver, you can use the `menuconfig` target to enable a driver that you need.
> 
> As this is not something specific to this kernel, closing.

But bro when i plugged my Pendrive it didn't detect.

**Comment by nathanchance** [comment]
That is not related to the kernel.

https://docs.microsoft.com/en-us/windows/wsl/wsl2-mount-disk
