### ISSUE TITLE
[Feature request] bash cripts for homemade bzImage

### ISSUE THREAD

**Issue by LeCmnGend** [nathanchance/WSL2-Linux-Kernel#24]
https://pastebin.com/9hUPSGFs
Here is my .sh file. hope we have general script file for normal user can build themselve

**Comment by nathanchance** [comment]
You do not need a fancy script to compile this kernel, it can be done with a simple make command. As of today:

```
make -j"$(nproc)" LLVM=/root/tc/proton/clang-15/bin/ O=out wsl2_defconfig bzImage
```

will do the same thing as your script. If you need to use `ccache`, it becomes a little bit more complicated:

```
PATH=/root/tc/proton/clang-15/bin:$PATH \
make -j"$(nproc)" \
CC="ccache clang" \
HOSTCC="ccache clang" \
LLVM=1 \
O=out \
wsl2_defconfig bzImage
```

That still does not justify a script that I won't use living in the tree.
