### ISSUE TITLE
Freezes/hangs when trying to mount an xfs formatted disk

### ISSUE THREAD

**Issue by klabit87** [nathanchance/WSL2-Linux-Kernel#26]
I have tested this against the stock WSL2 kernel (5.10.102.1-microsoft-standard-WSL2) and it works with no issues on the stock kernel but on your[ latest kernel](https://github.com/nathanchance/WSL2-Linux-Kernel/releases/tag/wsl2-cbl-kernel-next-20220405-vv64) when mounting a disk formatted as xfs, it freezes.  Only way to get unstuck is to kill wsl and restart.  Due to it freezing, I am not able to get logs.  I am still somewhat new to wsl so I may also not know of all the possible methods of grabbing a log.  I am not new to linux though.  Let me know how I can further assist you in resolving this please.
Thanks.

**Comment by nathanchance** [comment]
WSL2 is pretty much a black box when it comes to debugging anything. Unfortunately, I pretty much have no time to support this kernel (hence why there has not been a release in a couple of months) but you can try [this build](https://github.com/nathanchance/WSL2-Linux-Kernel/files/8787692/bzImage.gz) from the current next branch to see if it was an upstream issue that happened to get resolved.

**Comment by klabit87** [comment]
My apologies for the much delayed response, your build in the comment did resolve my xfs mount issues. Thank you.
