### ISSUE TITLE
What are the benefits of using a custom kernel?

### ISSUE THREAD

**Issue by haosmos** [nathanchance/WSL2-Linux-Kernel#27]
Hi! 😃

Sorry for the silly question — what are the benefits of using a custom kernel? Maybe some functionality appears which is not present in the standard Microsoft kernel or there are some performance improvements?

Could you at least briefly tell me what I can get by using your custom kernel?

**Comment by nathanchance** [comment]
The only reason I use a self-compiled Linux kernel is to be up to date with Linux upstream. I prefer to be as bleeding edge as possible to ensure there are no regressions that would impact me, as it is easier to catch problems when they happen versus further down the line.

I have been rather busy so I have not been publishing releases as frequently as I would like but the source is up to date if you want to compile it yourself.

**Comment by haosmos** [comment]
> The only reason I use a self-compiled Linux kernel is to be up to date with Linux upstream. I prefer to be as bleeding edge as possible to ensure there are no regressions that would impact me, as it is easier to catch problems when they happen versus further down the line.
> 
> I have been rather busy so I have not been publishing releases as frequently as I would like but the source is up to date if you want to compile it yourself.

So, in other words, there is no functional advantages or performance improvement in using wsl with the custom kernel? 

I use wsl for web development and want to understand if it makes sense to use a custom kernel.

**Comment by nathanchance** [comment]
I wouldn't expect there to be any functional or noticeable performance improvements with this kernel over the stock WSL2 one.

**Comment by haosmos** [comment]
> I wouldn't expect there to be any functional or noticeable performance improvements with this kernel over the stock WSL2 one.

Ok, thanks!
