### ISSUE TITLE
Enable KVM for nested virtualization

### ISSUE THREAD

**Issue by onomatopellan** [nathanchance/WSL2-Linux-Kernel#3]
Since insider build 19619 user can enable nested virtualization in WSL2 but kernel needs to have KVM enabled for Intel and AMD.

![image](https://user-images.githubusercontent.com/599142/84561790-a6c26200-ad4f-11ea-808a-fd5fc207e12a.png)

To enable nested virtualization add to the `.wslconfig` file
```
[wsl2]
nestedVirtualization=true
```
```bash
$ sudo kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

**Comment by nathanchance** [comment]
Sure, done in v32: https://github.com/nathanchance/WSL2-Linux-Kernel/commit/41399baaf9c2952f5d89b2de7e04b63895b9e4fc
