### ISSUE TITLE
EROFS not supported

### ISSUE THREAD

**Issue by amackpro** [nathanchance/WSL2-Linux-Kernel#30]

**Comment by nathanchance** [comment]
Does [this kernel](https://github.com/nathanchance/WSL2-Linux-Kernel/files/9244717/bzImage.zip) work for you? I just enabled `CONFIG_EROFS_FS`.

**Comment by amackpro** [comment]
> 

CONFIG_EROFS_FS=y
# CONFIG_EROFS_FS_DEBUG is not set
CONFIG_EROFS_FS_XATTR=y
CONFIG_EROFS_FS_POSIX_ACL=y
CONFIG_EROFS_FS_SECURITY=y
CONFIG_EROFS_FS_ZIP=y


These all needed to make erofs work perfectly

**Comment by nathanchance** [comment]
```
$ rg EROFS_FS .config
3420:CONFIG_EROFS_FS=y
3421:# CONFIG_EROFS_FS_DEBUG is not set
3422:CONFIG_EROFS_FS_XATTR=y
3423:CONFIG_EROFS_FS_POSIX_ACL=y
3424:CONFIG_EROFS_FS_SECURITY=y
3425:CONFIG_EROFS_FS_ZIP=y
3426:# CONFIG_EROFS_FS_ZIP_LZMA is not set
```

Those are the default values when just `CONFIG_EROFS_FS` is enabled.

**Comment by amackpro** [comment]
thanks for fixing the issue <3
