### ISSUE TITLE
dxgvmb_send_query_alloc_residency Error while Building.

### ISSUE THREAD

**Issue by mucookul** [nathanchance/WSL2-Linux-Kernel#31]
I recently reinstalled windows and now this error is coming, please help fix

**Comment by nathanchance** [comment]
You need to provide more information, such as an actual build error.

**Comment by mucookul** [comment]
![image](https://user-images.githubusercontent.com/71291707/195726500-fab687de-3368-4069-a58a-352c09af1758.png)

**Comment by nathanchance** [comment]
I'll look into this when I have time. Until then, either use LLVM like I do or remove `CONFIG_WERROR=y` from `arch/x86/configs/wsl2_defconfig`.

**Comment by mucookul** [comment]
I tried LLVM Clang and same error

**Comment by mucookul** [comment]
Error still coming with `CONFIG_WERROR=y` removed

**Comment by nathanchance** [comment]
> I tried LLVM Clang and same error

My tip of tree build does not show this (slightly outdated due to vacation):

```
$ clang --version | head -1
ClangBuiltLinux clang version 16.0.0 (https://github.com/llvm/llvm-project 7ec6dde83ae66b7b3a01c69d619970cd3280dfca)
```

> Error still coming with `CONFIG_WERROR=y` removed

Something else is going on then, as `-Werror` is only added with `CONFIG_WERROR`, which is not enabled by default. You should run `make mrproper` to make sure you are starting from a clean source then try again.

**Comment by mucookul** [comment]
they are still there but now warnings

**Comment by mucookul** [comment]
Why don't you use [ClangBuiltLinux/continuous-integration2](https://github.com/ClangBuiltLinux/continuous-integration2) to automate building for every commit

**Comment by mucookul** [comment]
just saying it would be easier to build with ci

**Comment by nathanchance** [comment]
This is a completely personal project, I am not interested in setting up continuous integration or anything. If it works for me locally, that is all that I care about.

**Comment by mucookul** [comment]
I thought the warnings may break something but from my testing nothing yet
