### ISSUE TITLE
How to compile inside WSL2 with Ubuntu 22.04?

### ISSUE THREAD

**Issue by VorlonCD** [nathanchance/WSL2-Linux-Kernel#32]
I'm on the latest build of Windows 11 22H2 with the very latest build of WSL2 from the Windows store, updated, with '**Ubuntu 22.04.1 LTS**' as the default distro.   Docker for WIndows also integrates itself.   I wouldnt call myself a Linux expert by any means but I have dabbled for a few years in WSL/Docker/Pihole type stuff.   Enough to be dangerous.

I've tried a number of things so far but this is basically where I am:

```
sudo -i
apt upgrade
apt update
apt install git bc build-essential flex bison libssl-dev libelf-dev
apt install clang
cd ~
git clone https://github.com/nathanchance/WSL2-Linux-Kernel.git
cd WSL2-Linux-Kernel
make -skj"$(nproc)" wsl2_defconfig bzImage
```

It chugs away for a while and near the end gave a few errors that flashed by and ended with these:

```
make[5]: *** [../scripts/Makefile.build:500: drivers/hv/dxgkrnl] Error 2
make[4]: *** [../scripts/Makefile.build:500: drivers/hv] Error 2
make[4]: *** Waiting for unfinished jobs....
...
make[3]: *** [../scripts/Makefile.build:500: drivers] Error 2
make[2]: *** [../Makefile:1992: .] Error 2
make[1]: *** [/root/WSL2-Linux-Kernel/Makefile:362: __build_one_by_one] Error 2
make[1]: Leaving directory '/root/WSL2-Linux-Kernel/out'
make: *** [Makefile:231: __sub-make] Error 2
```
clang --version gives me this:

```
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I saw one of your past examples refer to `/root/tc/proton/clang-15/bin/` but I couldnt figure out how to get that specific version of CLANG installed.

What is the right way to do this?

Thanks!!

**Comment by nathanchance** [comment]
I have just pushed an update to remove `CONFIG_WERROR=y` from my defconfig so this warning should not be fatal anymore.

You can get the update with `git remote update; git reset --hard origin/next` within the git repository.

After that, just run `make -skj"$(nproc)" mrproper wsl2_defconfig bzImage` and you should end up with the kernel at `arch/x86/boot/bzImage`.

**Comment by VorlonCD** [comment]
Thanks!   It got further:

```
WARNING: modpost: vmlinux.o: section mismatch in reference: callthunks_translate_call_dest.cold (section: .text.unlikely) -> skip_addr (section: .init.text)
WARNING: modpost: vmlinux.o: section mismatch in reference: callthunks_translate_call_dest.cold (section: .text.unlikely) -> patch_dest (section: .init.text)
WARNING: modpost: vmlinux.o: section mismatch in reference: is_callthunk.cold (section: .text.unlikely) -> skip_addr (section: .init.text)
ERROR: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.
make[2]: *** [scripts/Makefile.modpost:126: vmlinux.symvers] Error 1
make[2]: *** Deleting file 'vmlinux.symvers'
make[2]: Target '__modpost' not remade because of errors.
make[1]: *** [Makefile:1944: modpost] Error 2
make[1]: Target 'bzImage' not remade because of errors.
make: *** [Makefile:362: __build_one_by_one] Error 2
make: Target 'mrproper' not remade because of errors.
make: Target 'wsl2_defconfig' not remade because of errors.
make: Target 'bzImage' not remade because of errors.
```

**Comment by nathanchance** [comment]
Hmmm, that seems like a legitimate issue that should be reported upstream... I can handle that.

I forgot to include `LLVM=1` in the command to run so you are currently using GCC, which I do not test this kernel with. Use this one:

```
make -skj"$(nproc)" LLVM=1 mrproper wsl2_defconfig bzImage
```

Make sure that you have `clang`, `lld`, and `llvm` installed on your system.

**Comment by VorlonCD** [comment]
When I tried to install LLD it gave me this:

```
The following packages have unmet dependencies:
 libllvm16 : Depends: libffi6 (>= 3.0.4) but it is not installable
```

I was able to get it and LLVM installed after the first solution here:
https://stackoverflow.com/questions/69041576/the-following-packages-have-unmet-dependencies-when-installing-php8-0

It went a lot further and I saw this at the end after installing LLVM:

```
/sbin/ldconfig.real: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link

Scanning processes...
Scanning processor microcode...
Scanning linux images...

**Failed to retrieve available kernel versions.**

The processor microcode seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

Then ran make and got this:

```
ld.lld: error: Invalid value reference from metadata
ld.lld: error: Invalid value reference from metadata
ld.lld: error: Invalid value reference from metadata
make[2]: *** [scripts/Makefile.vmlinux_o:61: vmlinux.o] Error 1
make[2]: Target '__default' not remade because of errors.
make[1]: *** [Makefile:1229: vmlinux_o] Error 2
make[1]: Target 'bzImage' not remade because of errors.
make: *** [Makefile:362: __build_one_by_one] Error 2
make: Target 'mrproper' not remade because of errors.
make: Target 'wsl2_defconfig' not remade because of errors.
make: Target 'bzImage' not remade because of errors.


```

I forgot to mention WSL2 is currently using your last publicly released bzimage file if that could be a factor.

Unless you have further ideas I'm going to start fresh with new Ubuntu 22.04 distro without your bzimage, update it and install the apps again.

**Comment by nathanchance** [comment]
Did you add an LLVM repo to your apt sources? I would not expect to see that error with just Ubuntu's repos, unless they screwed up a package upgrade.

I have never seen `ld.lld: error: Invalid value reference from metadata` so it's probably just better to start over with a fresh distribution (you do not have to stop using my old kernel, it should not have any impact on this issue), just install the same packages that you did from the original post plus the ones I mentioned above, and go.

Just to make sure it works, I did the following:

```
PS C:\Users\natec> wsl --install Ubuntu --web-download
Downloading: Ubuntu
Installing: Ubuntu
Ubuntu has been installed.
Launching Ubuntu...
```

```
$ sudo sh -c "apt update && apt upgrade -y && apt install -y bc bison build-essential clang flex libssl-dev libelf-dev lld llvm"
...

$ git clone https://github.com/nathanchance/WSL2-Linux-Kernel
...

$ cd WSL2-Linux-Kernel

$ make -skj"$(nproc)" LLVM=1 mrproper wsl2_defconfig bzImage

$ ls arch/x86/boot/bzImage
arch/x86/boot/bzImage
```

**Comment by VorlonCD** [comment]
Great!   Starting from scratch appeared to work.  I assume something was messed up in my distro.
