### ISSUE TITLE
Homemade Build for WSl 2

### ISSUE THREAD

**Issue by jmauro** [nathanchance/WSL2-Linux-Kernel#4]
Hello @nathanchance,

I am really interested in your work on back porting the latest Linux kernel for WSL, but to be honest, I am a bit struggling to totally understand the process for building my own kernel on your `next` branch.
I have tried to use `bin/gen_wsl_config.sh` as well as `bin/build.sh` (I tried to customize this one to work with gcc).

Would you mind adding a bit of documentation into your own README? That would help a lot. 
Thanks in advance.

--
Kind regards,
JM

**NOTE**:  BTW, I was unable to boot your latest release (v47), but v46 works like a charm.

**Comment by nathanchance** [comment]
```
$ make -skj"$(nproc)" wsl2_defconfig bzImage
```

should be all you need to do to build the kernel with GCC; the image to use will be in `arch/x86/boot/bzImage`.

**Comment by haosmos** [comment]
> ```
> $ make -skj"$(nproc)" wsl2_defconfig bzImage
> ```
> 
> should be all you need to do to build the kernel with GCC; the image to use will be in `arch/x86/boot/bzImage`.

Hi! 

Tell me, please, how can I compile a core for my wsl2? 

Your answer is not very clear to me:  

```
$ make -skj"$(nproc)" wsl2_defconfig bzImage
All you need to do is to build the kernel with GCC; the image to use will be in arch/x86/boot/bzImage.
```

I need to download your repo (https://github.com/nathanchance/WSL2-Linux-Kernel.git), go to the WSL2-Linux-Kernel folder, then run the command: 
`make -skj"$(nproc)" wsl2_defconfig bzImage `

After compilation, take the image and place it in the user folder in windows and specify the path to this image in the .wslconfig file?

```
[wsl2]
kernel = C:\\Users\\<path-to-my-custom-wsl-kernel>
```

Or I can just download the last image from here https://github.com/nathanchance/wsl2-linux-kernel/releases and specify the path to it in my .wslconfig file?

**Comment by nathanchance** [comment]
> I need to download your repo (https://github.com/nathanchance/WSL2-Linux-Kernel.git), go to the WSL2-Linux-Kernel folder, then run the command:
> `make -skj"$(nproc)" wsl2_defconfig bzImage `
> 
> After compilation, take the image and place it in the user folder in windows and specify the path to this image in the .wslconfig file?
> 
> ```
> [wsl2]
> kernel = C:\\Users\\<path-to-my-custom-wsl-kernel>
> ```

Yes, this is the process if you would like to run your own compiled kernel from my sources.

> Or I can just download the last image from here https://github.com/nathanchance/wsl2-linux-kernel/releases and specify the path to it in my .wslconfig file?

This is also valid, if you just want to run my kernel without any work from yourself. This issue was specifically concerned with compiling a kernel on one's own machine.

**Comment by haosmos** [comment]
> > I need to download your repo ([nathanchance/WSL2-Linux-Kernel.git](https://github.com/nathanchance/WSL2-Linux-Kernel.git)), go to the WSL2-Linux-Kernel folder, then run the command:
> > `make -skj"$(nproc)" wsl2_defconfig bzImage `
> > After compilation, take the image and place it in the user folder in windows and specify the path to this image in the .wslconfig file?
> > ```
> > [wsl2]
> > kernel = C:\\Users\\<path-to-my-custom-wsl-kernel>
> > ```
> 
> Yes, this is the process if you would like to run your own compiled kernel from my sources.
> 
> > Or I can just download the last image from here [nathanchance/wsl2-linux-kernel/releases](https://github.com/nathanchance/wsl2-linux-kernel/releases) and specify the path to it in my .wslconfig file?
> 
> This is also valid, if you just want to run my kernel without any work from yourself. This issue was specifically concerned with compiling a kernel on one's own machine.

Thank you for the answer! 

Let me ask you a few more questions:

1. which wsl_defconfig file is used in your build? It must match the version of the Linux kernel you're compiling or it's optional and you can even use an outdated file, like this one: https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Microsoft/config-wsl.

2. your build includes a recent Microsoft patch: https://github.com/MicrosoftDocs/WSL/releases/tag/20175?

In particular, I am interested in this fix:

`Adjust default memory assignment of WSL2 VM to be 50% of host memory or 8GB, whichever is less [GH 4166].`

3. Your build allows you to run systemd?

**Comment by nathanchance** [comment]
> 1. which wsl_defconfig file is used in your build? It must match the version of the Linux kernel you're compiling or it's optional and you can even use an outdated file, like this one: https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Microsoft/config-wsl.

[`arch/x86/configs/wsl2_defconfig`](https://github.com/nathanchance/WSL2-Linux-Kernel/blob/639ff8b359de5d9d75e795d08c567764220fdbba/arch/x86/configs/wsl2_defconfig), which is [generated](https://github.com/nathanchance/WSL2-Linux-Kernel/blob/639ff8b359de5d9d75e795d08c567764220fdbba/bin/gen_wsl_config.sh) from Microsoft's configuration and modified by myself.

> 2. your build includes a recent Microsoft patch: https://github.com/MicrosoftDocs/WSL/releases/tag/20175?
> 
> In particular, I am interested in this fix:
> 
> `Adjust default memory assignment of WSL2 VM to be 50% of host memory or 8GB, whichever is less [GH 4166].`

I highly doubt that is a kernel patch; it is most likely something within the virtual machine code. Regardless, you can always just change the amount of memory that is assigned to the VM from `.wslconfig`.

> 3. Your build allows you to run systemd?

No idea. If there are kernel configs that need to be turned on to do this, I can look into them.

**Comment by haosmos** [comment]
@nathanchance, thank you for the answer! 

I installed your kernel and everything works fine! 

Regarding systemd activation, let me create a separate issue so that we don't discuss different issues in the same place.

**Comment by AntonOfTheWoods** [comment]
Thanks for your awesome work @nathanchance ! Now while I am shocked to find myself agreeing with @jmauro (ça va mec ? :-)), is there any chance of a note or readme somewhere? I wasted quite a lot of time before finding this ticket (I was about to create one) and see that it is incredibly easy to install and run a new kernel. I tried to extrapolate from https://nathanchance.dev/posts/wsl2-kernel-clang/ and it just didn't seem to work... A distillation of about 5 lines from this issue in an obvious place would certainly be sufficient!

**Comment by AntonOfTheWoods** [comment]
Thanks for your awesome work @nathanchance  ! Now while I am shocked to find myself agreeing with @jmauro  (ça va mec ? :-)), is there any chance of a note or readme somewhere? I wasted quite a lot of time before finding this ticket (I was about to create one) and see that it is incredibly easy to install and run a new kernel. I tried to extrapolate from https://nathanchance.dev/posts/wsl2-kernel-clang/ and it just didn't seem to work... A distillation of about 5 lines from this issue in an obvious place would certainly be sufficient!

**Comment by nathanchance** [comment]
@AntonOfTheWoods done: https://github.com/nathanchance/WSL2-Linux-Kernel/commit/6dcac587d828f4eb378e818ee33aad692e9915be

**Comment by AntonOfTheWoods** [comment]
@nathanchance , you are a gentleman and a scholar! When I get a moment i'll submit a PR for some instructions on how to build with support for wireguard, which was what got me started on this in the first place.

**Comment by nathanchance** [comment]
I can add WireGuard support to the kernel that I release, you should not need to build the kernel just for that. Are there any special configs that you need or just `CONFIG_WIREGUARD=y`?

**Comment by nathanchance** [comment]
I have enabled `CONFIG_WIREGUARD` in v53. If you have any more requests, do not hesitate to open an issue.

I think this issue has served its purpose, closing it up.

**Comment by AntonOfTheWoods** [comment]
You are a legend @nathanchance ! Works perfectly, thanks!

**Comment by gut5** [comment]
I tried building the "next" branch with `make -skj"$(nproc)" wsl2_defconfig bzImage` but the kernel that it produces gives the following error when you try to run the wsl command from a terminal:

`The operation timed out because a response was not received from the virtual machine or container.`

Like @jmauro I adapted the instruction from your blog. I separately tried to build with `make -j$(nproc) -s CC=clang-12 KCONFIG_CONFIG=Microsoft/config-wsl LD=ld.lld-12 distclean olddefconfig all` (clang and lld 12) but got a similar result.

This could be related but when I tried building the kernel with the LTO patches from samitolvanen I got a similar timeout error.

Does this build https://github.com/nathanchance/WSL2-Linux-Kernel/releases/tag/wsl2-cbl-kernel-next-20201029-v53 have LTO applied?

**Comment by nathanchance** [comment]
Yes, that build has LTO applied. You can check that by running `zgrep LTO /proc/config.gz`, where you should see `CONFIG_LTO_CLANG=y`.

I am not sure why it would not work but I do not have any cycles to figure that out.

**Comment by gut5** [comment]
~~Thanks, whatever you did fixed it and now the LTO kernel is compiling~~

**Comment by gut5** [comment]
Sorry about this, that was a false positive, the issue with the kernel not working still occurs on the new build.
WSL2 was still looking at the older kernel, not the new one I compiled.
