### ISSUE TITLE
Is it possible to activate systemd in your build by default? 

### ISSUE THREAD

**Issue by haosmos** [nathanchance/WSL2-Linux-Kernel#6]
For example, it will allow us to install snap packages (using snapd). 

At the moment there are several workarounds: 

1. https://github.com/arkane-systems/genie.

2. https://github.com/diddlesnaps/chsh-variant-wsl2-systemd

I found the kernel [fork](https://github.com/diddlesnaps/WSL2-Linux-Kernel/tree/snapd-support-5.4.y) where systemd is active by default if I understood correctly.  

But this is not the most up-to-date kernel used, unlike your fork. 

So, question: can you include systemd activation in your build? Or will it require a lot of work?

**Comment by nathanchance** [comment]
The fork looks like it adds a decent amount of code. I am fine with flipping configs on and such but I am not really interested in adding actual code to the kernel because that is maintenance that I have to take on because the upstream kernel moves pretty quick in terms of internal ABI changes.

**Comment by haosmos** [comment]
> The fork looks like it adds a decent amount of code. I am fine with flipping configs on and such but I am not really interested in adding actual code to the kernel because that is maintenance that I have to take on because the upstream kernel moves pretty quick in terms of internal ABI changes.

ok.
