### ISSUE TITLE
use this kernel, break docker desktop

### ISSUE THREAD

**Issue by khs1994** [nathanchance/WSL2-Linux-Kernel#7]
just pin issue

**Comment by nathanchance** [comment]
Can you be a little bit more specific as to the issue here? Like how does Docker Desktop break?

**Comment by nathanchance** [comment]
Stale issue, closing.

**Comment by AntonOfTheWoods** [comment]
I can also confirm that at least with v53, docker desktop 2.4.0 works fine. I can build and push to dockerhub no problem.

**Comment by nathanchance** [comment]
Thanks a lot for the testing and confirmation!
