### ISSUE TITLE
Enabling ALSA sound support with CONFIG_SOUND

### ISSUE THREAD

**Issue by pawelurbanski** [nathanchance/WSL2-Linux-Kernel#9]
Hi,
Your builds are fantastic and rightly refered all over the web. Since you are successful at building the latest upstream kernels I would like to ask about the following after a few unsuccessful attempts on my side:

What would be the proper config flags for enabling ALSA sound support?
Microsoft states in their docs the following:
To enable ALSA support you need at least to build the kernel with primary sound card support (CONFIG_SOUND). Since ALSA can emulate OSS, you don't have to choose any of the OSS modules.
Enable "OSS API emulation" (CONFIG_SND_OSSEMUL) and both OSS mixer and PCM supports if you want to run OSS applications with ALSA.
If you want to support the WaveTable functionality on cards such as SB Live! then you need to enable "Sequencer support" (CONFIG_SND_SEQUENCER).
https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Documentation/sound/alsa-configuration.rst

I've enabled the `CONFIG_SOUND` flag to y. There is no flag for wave tables, so I guess it does not matter in that case.
When build starts there are so many prompts for additional configuration values, which are not especially clear. Since this part is in teh Microsoft's repository it looks like direct sound support is possible without resorting to running pulse audio servers and so on - solutions are mostly about this server setup.

Any hints willbe very much appriciated...

**Comment by nathanchance** [comment]
My recommendation would be to add `CONFIG_SOUND=y` to your confit then run `olddefconfig` as your make target. That should allow you to avoid all of those prompts.
